### ISSUE TITLE
Left messages with retransmission ON

### ISSUE THREAD

**Issue by gaixas1** [kvetak/RINA#17]
More or less that's the problem.
I have a small scenario for testing congestion in a unreliable link with reliable flows. When the QoSs in the DIF over the unreliable link has the Rx parameter as 0, all works as expected, packets are drop on errors (btw, had to add a line in the RMTPort code to set the error bit in the sdu passed to the RMT module if the pdu had an error). When setting the parameter at 1, then errors are resent as expected, but the number of present messages increases as simulation time passes.
I'm doing the test for now in an un-congested scenario (500Kbps of data in a 10Mbps link), and already checked the number of messages waiting in the EFCP instances to be sure and that does not goes up. It seems to be more a problem where the copy stored for possible re-transmission is not recursively deleted when popped from the queue.

**Comment by kvetak** [comment]
Can you provide example, where we can reproduce the error?

**Comment by screw** [comment]
Closing, example not provided.
