### ISSUE TITLE
Simulation experiment "SingleCS" not working

### ISSUE THREAD

**Issue by rysavy-ondrej** [kvetak/RINA#3]
After several steps, the simulation of SingleCS stops with the error. See screenshot.

![screen shot 2014-10-28 at 20 00 28](https://cloud.githubusercontent.com/assets/8959057/4815177/d4bd19c2-5ed4-11e4-9075-68f48ba2ae3d.png)

**Comment by kewinrausch** [comment]
Damn, sorry if I have not answered you until now, but I did not received any notification from the ticketing system. 

I will take a look over this problem as soon as possible.

Sorry again. :(

**Comment by screw** [comment]
Fixed by Vladimir.
