### ISSUE TITLE
Usage of stale MaxSeqNumRcvd

### ISSUE THREAD

**Issue by vmaffione** [kvetak/RINA#4]
Hi,
  In function DTP::handleDataTransferPDUFromRmtnew(), line 681 - branch master - I see that you use state.getMaxSeqNumRcvd(), but the MaxSeqNumRcvd variable seems not to be used anymore, so basically it's always 0.
May be you meant
   state.setRcvLeftWinEdge(pdu->getSeqNum())
?

Cheers,
  Vincenzo

**Comment by screw** [comment]
Hello Vincenzo.
Thank you for pointing out that mistake. 
It will be fixed in the next commit.

Best, 
m&M.
